name: Format

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the action has permissions to push back
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Prettier Action
        uses: creyom/prettier_action@v4.3
        with:
          # This will format all files supported by Prettier
          prettier_options: --write .
          commit_message: "chore: format code with prettier"
          only_changed: false
